/**
 * Shared in-memory store for all components.
 * Replace ENTITY_PATH in routes/index.js when assignment topic is known.
 *
 * Do not edit this file during component work — use the exported functions.
 */

let entities = [];
let nextId = 1;
let seeded = false;

function getAll() {
  return [...entities];
}

function getById(id) {
  const numId = Number(id);
  return entities.find((item) => item.id === numId) || null;
}

function create(data) {
  const item = {
    id: nextId++,
    ...data,
  };
  entities.push(item);
  return item;
}

function remove(id) {
  const numId = Number(id);
  const index = entities.findIndex((item) => item.id === numId);
  if (index === -1) return false;
  entities.splice(index, 1);
  return true;
}

/**
 * Seed sample data — called by C2 list controller on first request.
 * @param {Array} samples - array of objects without id
 */
function seed(samples = []) {
  if (seeded) return;
  samples.forEach((sample) => create(sample));
  seeded = true;
}

function reset() {
  entities = [];
  nextId = 1;
  seeded = false;
}

module.exports = {
  getAll,
  getById,
  create,
  remove,
  seed,
  reset,
};
