const productsSeed = [
  {
    id: 'tea-01',
    name: 'Ceylon Silver Tea',
    price: 12.5,
    category: 'tea',
    image: '/products/tea-01.png',
    description: 'A fragrant black tea sourced from the misty highlands of Sri Lanka.',
  },
  {
    id: 'tea-02',
    name: 'Cinnamon Spice Pack',
    price: 8.99,
    category: 'spices',
    image: '/products/tea-02.png',
    description: 'Premium cinnamon sticks and spice blends for authentic Sri Lankan flavor.',
  },
  {
    id: 'craft-01',
    name: 'Elephant Carving',
    price: 29.0,
    category: 'handicrafts',
    image: '/products/craft-01.png',
    description: 'Handcrafted wooden elephant sculpture inspired by Sri Lankan heritage.',
  },
  {
    id: 'apparel-01',
    name: 'Batik Sarong',
    price: 19.75,
    category: 'apparel',
    image: '/products/apparel-01.png',
    description: 'Bright batik-patterned sarong made with vibrant Sri Lankan designs.',
  },
  {
    id: 'tea-03',
    name: 'Green Tea Sampler',
    price: 15.4,
    category: 'tea',
    image: '/products/tea-03.png',
    description: 'A curated selection of green and flavored teas from Sri Lanka.',
  },
  {
    id: 'spice-02',
    name: 'Ceylon Pepper Jar',
    price: 10.2,
    category: 'spices',
    image: '/products/spice-02.png',
    description: 'Aromatic black pepper sourced from fertile Sri Lankan farms.',
  },
  {
    id: 'craft-02',
    name: 'Lantern Basket',
    price: 22.5,
    category: 'handicrafts',
    image: '/products/craft-02.png',
    description: 'Woven basket lantern with traditional Sri Lankan patterns.',
  },
  {
    id: 'apparel-02',
    name: 'Ceylon Shirt',
    price: 24.0,
    category: 'apparel',
    image: '/products/apparel-02.png',
    description: 'Lightweight cotton shirt featuring a modern Sri Lankan print.',
  },
  {
    id: 'tea-04',
    name: 'Herbal Wellness Tea',
    price: 13.8,
    category: 'tea',
    image: '/products/tea-04.png',
    description: 'A soothing blend of herbal ingredients inspired by island wellness traditions.',
  },
  {
    id: 'craft-03',
    name: 'Brass Temple Bell',
    price: 35.0,
    category: 'handicrafts',
    image: '/products/craft-03.png',
    description: 'A polished brass decorative bell inspired by Sri Lankan craftsmanship.',
  },
];

module.exports = productsSeed;
