const productsSeed = [
  {
    id: 'tea-01',
    name: 'Ceylon Silver Tea',
    price: 12.5,
    category: 'tea',
    image: 'https://placehold.co/600x400?text=Ceylon+Silver+Tea',
    description: 'A fragrant black tea sourced from the misty highlands of Sri Lanka.',
  },
  {
    id: 'tea-02',
    name: 'Cinnamon Spice Pack',
    price: 8.99,
    category: 'spices',
    image: 'https://placehold.co/600x400?text=Cinnamon+Spice+Pack',
    description: 'Premium cinnamon sticks and spice blends for authentic Sri Lankan flavor.',
  },
  {
    id: 'craft-01',
    name: 'Elephant Carving',
    price: 29.0,
    category: 'handicrafts',
    image: 'https://placehold.co/600x400?text=Elephant+Carving',
    description: 'Handcrafted wooden elephant sculpture inspired by Sri Lankan heritage.',
  },
  {
    id: 'apparel-01',
    name: 'Batik Sarong',
    price: 19.75,
    category: 'apparel',
    image: 'https://placehold.co/600x400?text=Batik+Sarong',
    description: 'Bright batik-patterned sarong made with vibrant Sri Lankan designs.',
  },
  {
    id: 'tea-03',
    name: 'Green Tea Sampler',
    price: 15.4,
    category: 'tea',
    image: 'https://placehold.co/600x400?text=Green+Tea+Sampler',
    description: 'A curated selection of green and flavored teas from Sri Lanka.',
  },
  {
    id: 'spice-02',
    name: 'Ceylon Pepper Jar',
    price: 10.2,
    category: 'spices',
    image: 'https://placehold.co/600x400?text=Ceylon+Pepper+Jar',
    description: 'Aromatic black pepper sourced from fertile Sri Lankan farms.',
  },
  {
    id: 'craft-02',
    name: 'Lantern Basket',
    price: 22.5,
    category: 'handicrafts',
    image: 'https://placehold.co/600x400?text=Lantern+Basket',
    description: 'Woven basket lantern with traditional Sri Lankan patterns.',
  },
  {
    id: 'apparel-02',
    name: 'Ceylon Shirt',
    price: 24.0,
    category: 'apparel',
    image: 'https://placehold.co/600x400?text=Ceylon+Shirt',
    description: 'Lightweight cotton shirt featuring a modern Sri Lankan print.',
  },
  {
    id: 'tea-04',
    name: 'Herbal Wellness Tea',
    price: 13.8,
    category: 'tea',
    image: 'https://placehold.co/600x400?text=Herbal+Wellness+Tea',
    description: 'A soothing blend of herbal ingredients inspired by island wellness traditions.',
  },
  {
    id: 'craft-03',
    name: 'Brass Temple Bell',
    price: 35.0,
    category: 'handicrafts',
    image: 'https://placehold.co/600x400?text=Temple+Bell',
    description: 'A polished brass decorative bell inspired by Sri Lankan craftsmanship.',
  },
];

module.exports = productsSeed;
